# Generated by Django 4.0.3 on 2022-03-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualSanctionsTnvedCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanctions_tn_ved_code', models.CharField(max_length=15, verbose_name='Номер санкционного кода')),
                ('sanctions_tn_ved_code_description', models.TextField(blank=True, default='Description', verbose_name='Описание санкционного кода')),
            ],
            options={
                'verbose_name': 'Справочник санкционных кодов ТН ВЭД',
                'verbose_name_plural': 'Справочник санкционных кодов ТН ВЭД',
            },
        ),
        migrations.CreateModel(
            name='ActualTnvedDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tn_ved_code', models.CharField(max_length=15, verbose_name='Номер кода')),
                ('tn_ved_code_description', models.TextField(blank=True, default='Description', verbose_name='Описание кода')),
            ],
            options={
                'verbose_name': 'Справочник кодов ТН ВЭД',
                'verbose_name_plural': 'Справочник кодов ТН ВЭД',
            },
        ),
        migrations.CreateModel(
            name='CountriesAgainstRFRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code_2_dig', models.CharField(max_length=15, verbose_name='Код страны (2 символа)')),
            ],
            options={
                'verbose_name': 'Наименование страны',
                'verbose_name_plural': 'Наименование стран',
            },
        ),
        migrations.CreateModel(
            name='ResultTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code_2_dig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tn_ved_main.countriesagainstrfrb', verbose_name='Страна, которая ввела санкции')),
                ('sanctions_tn_ved_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tn_ved_main.actualsanctionstnvedcodes', verbose_name='Санкционный код ТН ВЭД')),
                ('tn_ved_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tn_ved_main.actualtnveddirectory', verbose_name='Код ТН ВЭД')),
            ],
            options={
                'verbose_name': 'Итоговая таблица',
                'verbose_name_plural': 'Итоговая таблица',
            },
        ),
        migrations.AddField(
            model_name='actualsanctionstnvedcodes',
            name='country_code_2_dig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tn_ved_main.countriesagainstrfrb', verbose_name='Код страны (2 символа)'),
        ),
    ]
