# Generated by Django 4.0.3 on 2022-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_ved_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctioncountrieslistfromru313',
            name='note',
            field=models.TextField(default='-', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='sanctionstnvedcodes',
            name='note',
            field=models.TextField(default='-', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='sanctionstnvedcodesfromru311312313by147',
            name='note',
            field=models.TextField(default='-', verbose_name='Примечание'),
        ),
    ]
