# Generated by Django 3.2.9 on 2022-05-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_ved_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanctionstnvedcodes',
            options={'verbose_name': 'Список санкционных кодов стран "Западного мира"', 'verbose_name_plural': 'Список санкционных кодов стран "Западного мира"'},
        ),
        migrations.AlterField(
            model_name='sanctionstnvedcodes',
            name='sanctions_tn_ved_code',
            field=models.CharField(db_index=True, max_length=250, verbose_name='CN код'),
        ),
        migrations.AlterField(
            model_name='sanctionstnvedcodesfromru311312313by147',
            name='sanctions_tn_ved_code',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Код ТН ВЭД ЕАЭС'),
        ),
    ]
