# Generated by Django 3.2.9 on 2022-05-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_ved_main', '0002_auto_20220526_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionstnvedcodes',
            name='export_import_ru',
            field=models.CharField(max_length=250, verbose_name='Экспорт в РФ / Импорт в РФ'),
        ),
    ]
