# Generated by Django 3.2.9 on 2022-05-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_ved_main', '0004_alter_sanctionstnvedcodes_sanctions_tn_ved_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionstnvedcodes',
            name='sanctions_tn_ved_code',
            field=models.CharField(db_index=True, max_length=1500, verbose_name='CN код'),
        ),
    ]
