# Generated by Django 3.2.9 on 2022-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tn_ved_main', '0005_alter_sanctionstnvedcodes_sanctions_tn_ved_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionstnvedcodes',
            name='country_code_2_dig_1side',
            field=models.CharField(max_length=6, verbose_name='Страна отправления'),
        ),
        migrations.AlterField(
            model_name='sanctionstnvedcodes',
            name='country_code_2_dig_2side',
            field=models.CharField(max_length=6, verbose_name='Страна назначения'),
        ),
    ]
